### ISSUE TITLE
crash on switch language

### ISSUE THREAD

**Issue by iamironrabbit** [zom/zom-ios-matrix#19]
Your app crashed on iPad running iOS 13.3.1 on WiFi when we:

- Tap “Switch language”

[attachment-5551114945162280881crashlog-486011D5-B837-4408-9EDD-22F0C9A03956.txt](https://github.com/zom/zom-ios-matrix/files/4376531/attachment-5551114945162280881crashlog-486011D5-B837-4408-9EDD-22F0C9A03956.txt)

**Comment by N-Pex** [comment]
Fixed.
